### ISSUE TITLE
[0] Error while getting the list of targets

### ISSUE THREAD

**Issue by rahulcivildp** [microsoft/vscode-edge-devtools#683] opened 2021-11-23 02:17 UTC
**Version:**
        1.4.1

        **OS:**
        

        **Stack :**
        Error: getaddrinfo ENOTFOUND wordpress

        **Additional context:**

**Comment by codepo8** [comment] 2021-12-01 18:26
Duplicate of #605

**Closed by codepo8** 2021-12-01 18:26 UTC
