### ISSUE TITLE
Can't launch Dev tools integration from remote session

### ISSUE THREAD

**Issue by gavinbarron** [microsoft/vscode-edge-devtools#438] opened 2021-07-21 17:26 UTC
Now this might be that my environment is just all kinds of messed up, but something is not working right.

Environment:
VSCode running in WSL2 (Ubuntu 20.4)
Edge hosted in Windows (Windows has 91.0.864.71, 93.0.946.1, and 93.0.958.0 installed but Version 91.0.864.71 is started only ever started with this config no matter what options I configure)
ms-edgedevtools.vscode-edge-devtools installed globally
![image](https://user-images.githubusercontent.com/7122716/126529392-46da4ba4-9677-49b5-9da7-01da6b60fc27.png)

Launch config:
```
    {
      "name": "Launch to Edge",
      "type": "pwa-msedge",
      "request": "launch",
      "port": 9222,
      "sourceMaps": true,
      "url": "http://localhost:9000/*",
      "webRoot": "${workspaceRoot}"
    }
```

When debugging clicking on the dev tools icon fails to launch the integrated dev tools pane and opens the extension pane with the query: @id:ms-edgedevtools.vscode-edge-devtools but this extension is already installed
![image](https://user-images.githubusercontent.com/7122716/126530135-415b21d1-ab9a-4474-97d9-d35c6a1097a9.png)

When checking the version of the launched browser it starts downloading updates and then fails:
![image](https://user-images.githubusercontent.com/7122716/126532671-b2432126-20b6-4e67-82d6-7bb02da5d8d4.png)

Extension Host Log:
```
[2021-07-21 09:55:20.479] [exthost] [info] extension host started
[2021-07-21 09:55:20.480] [exthost] [info] Skipping acquiring lock for c:\Users\LA\AppData\Roaming\Code\User\workspaceStorage\f0888b0b8e896f872aad793d74821b29.
[2021-07-21 09:55:20.508] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-wsl {"startup":false,"extensionId":{"value":"ms-vscode-remote.remote-wsl","_lower":"ms-vscode-remote.remote-wsl"},"activationEvent":"onResolveRemoteAuthority:wsl"}
[2021-07-21 09:55:20.508] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/LA/.vscode/extensions/ms-vscode-remote.remote-wsl-0.58.2/dist/extension
[2021-07-21 09:55:24.552] [exthost] [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication {"startup":false,"extensionId":{"value":"vscode.microsoft-authentication","_lower":"vscode.microsoft-authentication"},"activationEvent":"onAuthenticationRequest:microsoft"}
[2021-07-21 09:55:24.553] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/LA/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/microsoft-authentication/dist/extension.js
[2021-07-21 09:55:24.567] [exthost] [info] ExtensionService#_doActivateExtension Equinusocio.vsc-material-theme {"startup":true,"extensionId":{"value":"Equinusocio.vsc-material-theme","_lower":"equinusocio.vsc-material-theme"},"activationEvent":"*"}
[2021-07-21 09:55:24.567] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/LA/.vscode/extensions/equinusocio.vsc-material-theme-33.1.2/build/material.theme.config
[2021-07-21 09:55:24.694] [exthost] [info] ExtensionService#_doActivateExtension equinusocio.vsc-material-theme-icons {"startup":true,"extensionId":{"value":"equinusocio.vsc-material-theme-icons","_lower":"equinusocio.vsc-material-theme-icons"},"activationEvent":"*"}
[2021-07-21 09:55:24.694] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/LA/.vscode/extensions/equinusocio.vsc-material-theme-icons-1.2.2/out/src/extension
[2021-07-21 09:55:24.837] [exthost] [info] ExtensionService#_doActivateExtension johnpapa.vscode-peacock {"startup":true,"extensionId":{"value":"johnpapa.vscode-peacock","_lower":"johnpapa.vscode-peacock"},"activationEvent":"*"}
[2021-07-21 09:55:24.837] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/LA/.vscode/extensions/johnpapa.vscode-peacock-3.9.1/dist/extension
[2021-07-21 09:55:24.869] [exthost] [info] ExtensionService#_doActivateExtension Shan.code-settings-sync {"startup":true,"extensionId":{"value":"Shan.code-settings-sync","_lower":"shan.code-settings-sync"},"activationEvent":"*"}
[2021-07-21 09:55:24.870] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/LA/.vscode/extensions/shan.code-settings-sync-3.4.3/out/extension.js
[2021-07-21 09:55:25.728] [exthost] [info] ExtensionService#_doActivateExtension vscode-icons-team.vscode-icons {"startup":true,"extensionId":{"value":"vscode-icons-team.vscode-icons","_lower":"vscode-icons-team.vscode-icons"},"activationEvent":"*"}
[2021-07-21 09:55:25.730] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/LA/.vscode/extensions/vscode-icons-team.vscode-icons-11.5.0/dist/src/vscode-icons.bundle.js
[2021-07-21 09:55:25.885] [exthost] [info] ExtensionService#_doActivateExtension zhuangtongfa.material-theme {"startup":true,"extensionId":{"value":"zhuangtongfa.material-theme","_lower":"zhuangtongfa.material-theme"},"activationEvent":"*"}
[2021-07-21 09:55:25.885] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/LA/.vscode/extensions/zhuangtongfa.material-theme-3.11.1/out/extension.js
[2021-07-21 09:55:27.150] [exthost] [info] ExtensionService#_doActivateExtension vscode.github-authentication {"startup":false,"extensionId":{"value":"vscode.github-authentication","_lower":"vscode.github-authentication"},"activationEvent":"onAuthenticationRequest:github"}
[2021-07-21 09:55:27.150] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/LA/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/github-authentication/dist/extension.js
[2021-07-21 09:55:34.186] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-containers {"startup":false,"extensionId":{"value":"ms-vscode-remote.remote-containers","_lower":"ms-vscode-remote.remote-containers"},"activationEvent":"onStartupFinished"}
[2021-07-21 09:55:34.186] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/LA/.vscode/extensions/ms-vscode-remote.remote-containers-0.187.1/dist/extension/extension
[2021-07-21 09:55:40.746] [exthost] [error] Activating extension vscode-icons-team.vscode-icons failed due to an error:
[2021-07-21 09:55:40.746] [exthost] [error] Error: ENOENT: no such file or directory, open 'C:\home\gavinb\dev\events\client\eslint-rules\event-tools-rules\package.json'
[2021-07-21 09:55:40.746] [exthost] [info] eager extensions activated

```

Remote Extension Log:
```
[2021-07-21 09:55:24.925] [exthost] [info] extension host started
[2021-07-21 09:55:24.955] [exthost] [info] Lock '/home/gavinb/.vscode-server/data/User/workspaceStorage/f0888b0b8e896f872aad793d74821b29/vscode.lock': Lock acquired.
[2021-07-21 09:55:25.191] [exthost] [info] ExtensionService#_doActivateExtension vscode.extension-editing {"startup":false,"extensionId":{"value":"vscode.extension-editing","_lower":"vscode.extension-editing"},"activationEvent":"onLanguage:typescript"}
[2021-07-21 09:55:25.191] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/gavinb/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679adfb3/extensions/extension-editing/dist/extensionEditingMain
[2021-07-21 09:55:25.214] [exthost] [info] ExtensionService#_doActivateExtension vscode.typescript-language-features {"startup":false,"extensionId":{"value":"vscode.typescript-language-features","_lower":"vscode.typescript-language-features"},"activationEvent":"onLanguage:typescript"}
[2021-07-21 09:55:25.214] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/gavinb/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679adfb3/extensions/typescript-language-features/dist/extension
[2021-07-21 09:55:25.267] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"extensionId":{"value":"vscode.debug-auto-launch","_lower":"vscode.debug-auto-launch"},"activationEvent":"*"}
[2021-07-21 09:55:25.267] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/gavinb/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679adfb3/extensions/debug-auto-launch/dist/extension
[2021-07-21 09:55:25.274] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2021-07-21 09:55:25.274] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/gavinb/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679adfb3/extensions/git/dist/main
[2021-07-21 09:55:25.369] [exthost] [info] ExtensionService#_doActivateExtension firsttris.vscode-jest-runner {"startup":true,"extensionId":{"value":"firsttris.vscode-jest-runner","_lower":"firsttris.vscode-jest-runner"},"activationEvent":"*"}
[2021-07-21 09:55:25.369] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/gavinb/.vscode-server/extensions/firsttris.vscode-jest-runner-0.4.44/dist/extension
[2021-07-21 09:55:25.694] [exthost] [info] ExtensionService#_doActivateExtension GitHub.copilot {"startup":true,"extensionId":{"value":"GitHub.copilot","_lower":"github.copilot"},"activationEvent":"*"}
[2021-07-21 09:55:25.694] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/gavinb/.vscode-server/extensions/github.copilot-1.2.2064/dist/extension
[2021-07-21 09:55:25.877] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.test-adapter-converter {"startup":true,"extensionId":{"value":"hbenl.vscode-test-explorer","_lower":"hbenl.vscode-test-explorer"},"activationEvent":"*"}
[2021-07-21 09:55:25.877] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/gavinb/.vscode-server/extensions/ms-vscode.test-adapter-converter-0.0.13/out/extension.js
[2021-07-21 09:55:25.917] [exthost] [info] ExtensionService#_doActivateExtension joelday.docthis {"startup":true,"extensionId":{"value":"joelday.docthis","_lower":"joelday.docthis"},"activationEvent":"*"}
[2021-07-21 09:55:25.917] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/gavinb/.vscode-server/extensions/joelday.docthis-0.7.1/out/src/extension
[2021-07-21 09:55:26.215] [exthost] [info] ExtensionService#_doActivateExtension ms-vsliveshare.vsliveshare {"startup":true,"extensionId":{"value":"ms-vsliveshare.vsliveshare","_lower":"ms-vsliveshare.vsliveshare"},"activationEvent":"*"}
[2021-07-21 09:55:26.215] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/gavinb/.vscode-server/extensions/ms-vsliveshare.vsliveshare-1.0.4583/out/prod/extension-prod
[2021-07-21 09:55:26.687] [exthost] [info] ExtensionService#_doActivateExtension ryanluker.vscode-coverage-gutters {"startup":true,"extensionId":{"value":"ryanluker.vscode-coverage-gutters","_lower":"ryanluker.vscode-coverage-gutters"},"activationEvent":"*"}
[2021-07-21 09:55:26.687] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/gavinb/.vscode-server/extensions/ryanluker.vscode-coverage-gutters-2.8.0/out/src/extension
[2021-07-21 09:55:27.043] [exthost] [info] ExtensionService#_doActivateExtension streetsidesoftware.code-spell-checker {"startup":true,"extensionId":{"value":"streetsidesoftware.code-spell-checker","_lower":"streetsidesoftware.code-spell-checker"},"activationEvent":"*"}
[2021-07-21 09:55:27.043] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/gavinb/.vscode-server/extensions/streetsidesoftware.code-spell-checker-1.10.2/dist/extension.js
[2021-07-21 09:55:27.427] [exthost] [info] ExtensionService#_doActivateExtension vscode.npm {"startup":true,"extensionId":{"value":"vscode.npm","_lower":"vscode.npm"},"activationEvent":"workspaceContains:package.json"}
[2021-07-21 09:55:27.427] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/gavinb/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679adfb3/extensions/npm/dist/npmMain
[2021-07-21 09:55:27.475] [exthost] [info] ExtensionService#_doActivateExtension Orta.vscode-jest {"startup":true,"extensionId":{"value":"Orta.vscode-jest","_lower":"orta.vscode-jest"},"activationEvent":"workspaceContains:jest.config.js"}
[2021-07-21 09:55:27.475] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/gavinb/.vscode-server/extensions/orta.vscode-jest-4.0.3/out/extension
[2021-07-21 09:55:30.418] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.js-debug {"startup":false,"extensionId":{"value":"ms-vscode.js-debug","_lower":"ms-vscode.js-debug"},"activationEvent":"onCommand:extension.js-debug.clearAutoAttachVariables"}
[2021-07-21 09:55:30.418] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/gavinb/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679adfb3/extensions/ms-vscode.js-debug/src/extension.js
[2021-07-21 09:55:30.755] [exthost] [info] ExtensionService#_doActivateExtension vscode.github {"startup":false,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2021-07-21 09:55:30.755] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/gavinb/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679adfb3/extensions/github/dist/extension.js
[2021-07-21 09:55:30.769] [exthost] [info] ExtensionService#_doActivateExtension hbenl.vscode-test-explorer {"startup":false,"extensionId":{"value":"raagh.angular-karma-test-explorer","_lower":"raagh.angular-karma-test-explorer"},"activationEvent":"*"}
[2021-07-21 09:55:30.769] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/gavinb/.vscode-server/extensions/hbenl.vscode-test-explorer-2.20.4/out/main.js
[2021-07-21 09:55:35.738] [exthost] [info] ExtensionService#_doActivateExtension raagh.angular-karma-test-explorer {"startup":true,"extensionId":{"value":"raagh.angular-karma-test-explorer","_lower":"raagh.angular-karma-test-explorer"},"activationEvent":"*"}
[2021-07-21 09:55:35.738] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/gavinb/.vscode-server/extensions/raagh.angular-karma-test-explorer-1.2.8/out/main.js
[2021-07-21 09:55:38.742] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":false,"extensionId":{"value":"vscode.emmet","_lower":"vscode.emmet"},"activationEvent":"onStartupFinished"}
[2021-07-21 09:55:38.743] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/gavinb/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679adfb3/extensions/emmet/dist/node/emmetNodeMain
[2021-07-21 09:55:38.759] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":false,"extensionId":{"value":"vscode.merge-conflict","_lower":"vscode.merge-conflict"},"activationEvent":"onStartupFinished"}
[2021-07-21 09:55:38.759] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/gavinb/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679adfb3/extensions/merge-conflict/dist/mergeConflictMain
[2021-07-21 09:55:38.773] [exthost] [info] ExtensionService#_doActivateExtension vscode.testing-editor-contributions {"startup":false,"extensionId":{"value":"vscode.testing-editor-contributions","_lower":"vscode.testing-editor-contributions"},"activationEvent":"onStartupFinished"}
[2021-07-21 09:55:38.774] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/gavinb/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679adfb3/extensions/testing-editor-contributions/dist/extension.js
[2021-07-21 09:55:38.775] [exthost] [info] ExtensionService#_doActivateExtension dbaeumer.vscode-eslint {"startup":false,"extensionId":{"value":"dbaeumer.vscode-eslint","_lower":"dbaeumer.vscode-eslint"},"activationEvent":"onStartupFinished"}
[2021-07-21 09:55:38.775] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/gavinb/.vscode-server/extensions/dbaeumer.vscode-eslint-2.1.23/client/out/extension
[2021-07-21 09:55:38.882] [exthost] [info] ExtensionService#_doActivateExtension eamodio.gitlens {"startup":false,"extensionId":{"value":"eamodio.gitlens","_lower":"eamodio.gitlens"},"activationEvent":"onStartupFinished"}
[2021-07-21 09:55:38.882] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/gavinb/.vscode-server/extensions/eamodio.gitlens-11.6.0/dist/gitlens
[2021-07-21 09:55:39.286] [exthost] [info] ExtensionService#_doActivateExtension esbenp.prettier-vscode {"startup":false,"extensionId":{"value":"esbenp.prettier-vscode","_lower":"esbenp.prettier-vscode"},"activationEvent":"onStartupFinished"}
[2021-07-21 09:55:39.286] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/gavinb/.vscode-server/extensions/esbenp.prettier-vscode-8.0.1/dist/extension
[2021-07-21 09:55:40.675] [exthost] [info] eager extensions activated
[2021-07-21 09:55:55.901] [exthost] [info] ExtensionService#_doActivateExtension vscode.configuration-editing {"startup":false,"extensionId":{"value":"vscode.configuration-editing","_lower":"vscode.configuration-editing"},"activationEvent":"onLanguage:jsonc"}
[2021-07-21 09:55:55.902] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/gavinb/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679adfb3/extensions/configuration-editing/dist/configurationEditingMain
[2021-07-21 09:55:55.906] [exthost] [info] ExtensionService#_doActivateExtension vscode.json-language-features {"startup":false,"extensionId":{"value":"vscode.json-language-features","_lower":"vscode.json-language-features"},"activationEvent":"onLanguage:jsonc"}
[2021-07-21 09:55:55.906] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/gavinb/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679adfb3/extensions/json-language-features/client/dist/node/jsonClientMain
[2021-07-21 09:55:55.988] [exthost] [info] ExtensionService#_doActivateExtension ms-dotnettools.vscode-dotnet-runtime {"startup":false,"extensionId":{"value":"msazurermtools.azurerm-vscode-tools","_lower":"msazurermtools.azurerm-vscode-tools"},"activationEvent":"onLanguage:jsonc"}
[2021-07-21 09:55:55.988] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/gavinb/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.2.0/dist/extension.js
[2021-07-21 09:55:56.291] [exthost] [info] ExtensionService#_doActivateExtension msazurermtools.azurerm-vscode-tools {"startup":false,"extensionId":{"value":"msazurermtools.azurerm-vscode-tools","_lower":"msazurermtools.azurerm-vscode-tools"},"activationEvent":"onLanguage:jsonc"}
[2021-07-21 09:55:56.291] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/gavinb/.vscode-server/extensions/msazurermtools.azurerm-vscode-tools-0.15.2/main
[2021-07-21 09:57:45.874] [exthost] [warning] TextEditor is closed/disposed
```

**Comment by gavinbarron** [comment] 2021-07-21 17:38
Worth noting that if I run debugger config from Windows it launches the debugging session and opens the dev tools as expected

**Comment by deckchairlabs** [comment] 2021-07-24 01:51
I am also experiencing this issue, launching of Edge browser and the Javascript debugger are attaching correctly. The "Open Browser Devtools" action in the debug overlay widget will just prompt to install "ms-edgedevtools.vscode-edge-devtools" extension, even though it is installed.

**Comment by deckchairlabs** [comment] 2021-07-24 01:52
Also note, I did not experience the Edge update issue.

Running Edge: Version 92.0.902.55 (Official build) (64-bit)

**Comment by deckchairlabs** [comment] 2021-07-24 01:57
Seems to be related to https://github.com/microsoft/vscode-js-debug/issues/1024

**Comment by deckchairlabs** [comment] 2021-07-24 02:30
And most definitely a duplicate of https://github.com/microsoft/vscode-edge-devtools/issues/413

**Comment by bgoddar** [comment] 2021-08-19 19:31
Sorry for the delayed responses. We have added some support for remote workspaces with the 1.2.1 version of the extension. Please update and let us know if things are working for you now, or if there are still issues.

https://github.com/microsoft/vscode-edge-devtools/pull/444

**Comment by captainbrosset** [comment] 2022-02-01 10:24
This has unfortunately gotten stale. I'm assuming that @bgoddar's comment above means the problem is fixed, so I'm closing this issue.

**Closed by captainbrosset** 2022-02-01 10:24 UTC
