### ISSUE TITLE
Use Chrome extensions in Edge for VS Code

### ISSUE THREAD

**Issue by Suniron** [microsoft/vscode-edge-devtools#1552] opened 2023-06-05 07:33 UTC
**Describe the solution you'd like:**
I want a way to use a Chrome extension in this Vscode Edge browser. In my case, I want the Vue.js devtools extension.

**Describe alternatives you've considered:**
Currently, I have to use the desktop browser if I want to debug Vue.js

**Comment by captainbrosset** [comment] 2023-06-05 07:51
Thanks for your interest. This is something the team is already tracking in #1039. So I'll close this one as a duplicate of that one.

**Closed by captainbrosset** 2023-06-05 07:51 UTC
