### ISSUE TITLE
Issue using Dev Tool: BlobNotFoundThe specified blob does not exist. RequestId:51b37142-001e-0046-202a-0bc6a6000000 Time:2022-12-08T17:25:40.4338850Z

### ISSUE THREAD

**Issue by PublicTrades** [microsoft/vscode-edge-devtools#1284] opened 2022-12-08 17:31 UTC
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10): macOS
 - Extension version (*e.g.,* 1.2.3): v2.1.1

**Describe the bug:**

After Installation and launching the extension, Edge DevTool displayed this message:
BlobNotFoundThe specified blob does not exist. RequestId:51b37142-001e-0046-202a-0bc6a6000000 Time:2022-12-08T17:25:40.4338850Z

**Repro steps:**

**Expected behavior:**

To be able to see and inspect the dev tool

**Additional context:**

**Comment by captainbrosset** [comment] 2022-12-09 09:19
Thanks for filing. I think this is a duplicate of this other issue: #1243. So I'll close this one for now. If you believe this is different, please let me know.

**Closed by captainbrosset** 2022-12-09 09:19 UTC

**Comment by PublicTrades** [comment] 2022-12-09 14:22
Okay, so its a duplicate of the other issue, but what's the solution, how do I resolve this issue?

**Comment by captainbrosset** [comment] 2022-12-09 14:59
Sorry if I wasn't clear. I've closed this one as a duplicate, but the other one is still open. This means the issue still exist in the codebase, and the team will need to make the right fix and release a new version for it to be fixed for you.

**Comment by PublicTrades** [comment] 2022-12-09 16:29
I see. Thanks
