### ISSUE TITLE
VS code not working properly

### ISSUE THREAD

**Issue by RushiKale77** [microsoft/vscode-edge-devtools#1527] opened 2023-05-16 10:03 UTC
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

![2023-05-16](https://github.com/microsoft/vscode-edge-devtools/assets/124054829/264690f6-a0ec-4614-8a26-fd6d365363ad)

![2023-05-16 (1)](https://github.com/microsoft/vscode-edge-devtools/assets/124054829/a6d39f64-3699-444e-9fb0-23f978291d8f)
![2023-05-16 (2)](https://github.com/microsoft/vscode-edge-devtools/assets/124054829/c4141143-6d64-45ac-bedc-3f05bdf35291)

**Comment by captainbrosset** [comment] 2023-05-17 09:05
Thank you for filing this issue.
It's not immediately clear to me, from the screenshots, what the problem is. I do see an error in the first screenshot, but I don't know where it could be coming from without a description of the steps you took to get there.
Could you please add a comment here explaining what you were doing, what you expected to happened, and what happened instead?

**Comment by vidorteg** [comment] 2023-06-09 18:56
I think this is more related to vscode not behaving as expected. Closing for now, feel free to reopen if there is new information available

**Closed by vidorteg** 2023-06-09 18:56 UTC
