### ISSUE TITLE
visual code new microsoft extensiom having an one issue when i am one the microsoft extension new blank screen apper on the screen that is not useful screen what do

### ISSUE THREAD

**Issue by GOWTHAM2928** [microsoft/vscode-edge-devtools#2476] opened 2024-10-08 23:31 UTC
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by vidorteg** [comment] 2024-10-09 18:24
Hi and thanks for reporting, 
This seems a duplicate of 
https://github.com/microsoft/vscode-edge-devtools/issues/2445

Please feel free to continue discussion over there.

**Closed by vidorteg** 2024-10-09 18:24 UTC
