### ISSUE TITLE
live server is not working

### ISSUE THREAD

**Issue by Arpitamo** [microsoft/vscode-edge-devtools#2119] opened 2024-04-14 05:31 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by captainbrosset** [comment] 2024-04-15 14:24
Thanks for reaching out. I'm going to close this as a duplicate of https://github.com/microsoft/vscode-edge-devtools/issues/1453.

**Closed by captainbrosset** 2024-04-15 14:24 UTC
