### ISSUE TITLE
Couldn't attach to http://localhost.

### ISSUE THREAD

**Issue by wazybr** [microsoft/vscode-edge-devtools#172] opened 2020-06-30 16:56 UTC
When I open Edge from the "+" button in the Elements for Microsoft Edge sidepanel, the "Elements" panel doesn't attach to the new Edge instance. Edge is being launched properly with the remote debugging port command line argument.

Here's the entire command (got it from `edge://version`):
```
"C:\Program Files (x86)\Microsoft\Edge Dev\Application\msedge.exe" --user-data-dir="C:\Users\Wazy\AppData\Local\Microsoft\Edge Dev\User Data" --no-first-run --no-default-browser-check --remote-debugging-port=9222 --flag-switches-begin --enable-experimental-web-platform-features --javascript-harmony --enable-features=NativeFileSystemAPI --flag-switches-end --enable-audio-service-sandbox http://localhost
```

Trying to attach to a running Edge instance (with the proper command line arguments) doesn't work either.

In all the two cases, the "Elements" panel show up, but it's empty:

![image](https://user-images.githubusercontent.com/49368302/86153921-bc1de700-bad8-11ea-8d57-e2b3ad3c0bb8.png)

Sometimes the `Couldn't attach to http://localhost` error pops up. I think it's not showing this error anymore because I dismissed the popup.

### Environment info:
Version: 1.47.0-insider (user setup)
Commit: 04203498480e48be84d86f5763e126c7c5bf22e0
Date: 2020-06-30T09:00:22.588Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by mliao95** [comment] 2020-07-01 19:18
Is this the extension from the store or is it the latest version in this repository?

**Comment by mliao95** [comment] 2020-07-01 19:43
Update:  Just tried the insiders version with the tip of this repo and I am seeing your issue.  Investigating.

**Comment by wazybr** [comment] 2020-07-01 21:05
@mliao95 It was from the store. Thanks for looking into this.

**Comment by mliao95** [comment] 2020-07-17 01:26
Hey @wazybr, I wanted to post a follow up that we are still investigating this issue.  

There has been a recent change in the way vscode loads resources that has affected the way this extension operates.  Unfortunately, that change has made its way into VSCode stable (1.47.2) so the current extension is not compatible with VSCode.  However, it appears there is a new patch in the current version of VSCode Insiders (1.48.0) that fixes the issues with this extension.  The current workaround now would be to use VSCode Insiders to run this extension.

**Comment by wazybr** [comment] 2020-07-17 01:37
@mliao95 Alright. Thanks for the heads up.

**Comment by vidorteg** [comment] 2020-08-04 01:18
This seems to be a duplicate of:
https://github.com/microsoft/vscode-edge-devtools/issues/179

a fix for this will land soon.

**Closed by vidorteg** 2020-08-04 01:18 UTC
Labels: bug
