### ISSUE TITLE
[0] Error while getting the list of targets

### ISSUE THREAD

**Issue by Loongtech** [microsoft/vscode-edge-devtools#656] opened 2021-11-17 02:28 UTC
**Version:**
        1.4.1

        **OS:**
        

        **Stack :**
        Error: Parse Error: Expected HTTP/

        **Additional context:**

**Comment by codepo8** [comment] 2021-11-19 12:57
No extra information given

Duplicate of #605

**Closed by codepo8** 2021-11-19 12:57 UTC
