### ISSUE TITLE
live server

### ISSUE THREAD

**Issue by glyndelcuesta** [microsoft/vscode-edge-devtools#2058] opened 2024-03-07 16:17 UTC
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by glyndelcuesta** [comment] 2024-03-07 16:18
never run the live server

**Comment by captainbrosset** [comment] 2024-03-08 10:09
Closing as a duplicate of #1453.

**Closed by captainbrosset** 2024-03-08 10:09 UTC
