### ISSUE TITLE
[0] Error while fetching list of available targets

### ISSUE THREAD

**Issue by Rahman2001** [microsoft/vscode-edge-devtools#652] opened 2021-11-16 17:46 UTC
**Version:**
        1.4.1

        **OS:**
        Windows 10 Home Single Language
        

        **Stack :**
        No available targets to attach.

        **Additional context:**

**Comment by codepo8** [comment] 2021-11-19 12:53
No extra information given

Duplicate of #610

**Closed by codepo8** 2021-11-19 12:53 UTC
