### ISSUE TITLE
Breakpoints shown as unbounded breakpoints in react project

### ISSUE THREAD

**Issue by ja-why-son** [microsoft/vscode-edge-devtools#826] opened 2022-01-20 00:31 UTC
**Environment :**
 - OS : Windows 11
 - Extension version: 1.4.2

**Describe the bug:**
The breakpoints set in vscode is shown as unbounded breakpoints while using the edge tool. 

**Repro steps:**
Debug a react project using edge tool will make the breakpoints unbounded breakpoints.

**Expected behavior:**
Should be able to debug just like using "source" tab in browser dev tool.

**Comment by codepo8** [comment] 2022-01-24 15:30
Thank you for your report. We will look into it.

**Comment by bwalderman** [comment] 2022-02-07 23:55
@ja-why-son, I was able to debug with breakpoints using this simple react project: https://github.com/bwalderman/react-typescript-webpack. Can you share a git repo or code sample that reproduces the problem? The launch.json configuration you are using would also be helpful.

**Comment by bwalderman** [comment] 2022-02-11 18:11
Since debugging appears to work in the React projects I've tried and since there hasn't been any further replies, I will need to close this issue. Please feel free to reply again if you have more information.

**Closed by bwalderman** 2022-02-11 18:11 UTC
Labels: bug, tracked
