### ISSUE TITLE
False positive axe/structure errors in JSX with dl and React fragments

### ISSUE THREAD

**Issue by joelspadin** [microsoft/vscode-edge-devtools#615] opened 2021-11-07 01:07 UTC
**Environment (please complete the following information):**
 - OS: Windows 10
 - Extension version (*e.g.,* 1.2.3): 1.4.1

**Describe the bug:**

In React code with `dl` lists generated with React fragments, I get the following error:

    <dl> elements must only directly contain properly-ordered <dt> and <dd> groups, <script>, <template> or <div> elementsMicrosoft Edge Toolsaxe/structure

![image](https://user-images.githubusercontent.com/760836/140628278-72ef853a-bc18-4958-82de-06fc632f4a55.png)

**Repro steps:**
Write JSX/TSX code that generates a `dl` list using fragments.

```tsx
const TestComponent: React.FC = () => {
    const items = [1, 2, 3];

    return (
        <dl>
            {items.map((x, i) => (
                <React.Fragment key={i}>
                    <dt>{x}</dt>
                    <dd>{x}</dd>
                </React.Fragment>
            ))}
        </dl>
    );
};
```

**Expected behavior:**
The above code generates a valid `dl` list, containing only `dt` elements followed by `dd` elements. It should not be an error.

**Additional context:**

**Comment by antross** [comment] 2021-11-08 23:50
Thanks for reporting @joelspadin! I've confirmed I'm seeing the issue. Looks like this will need to be fixed in the webhint project (which I also work on) so I've created a copy of this issue to follow up on there: https://github.com/webhintio/hint/issues/4878.

**Comment by antross** [comment] 2021-11-17 19:32
FYI @joelspadin, this false-positive should be fixed now (has been addressed in the webhint project and an update released). Thanks again for the report!

**Closed by antross** 2021-11-17 19:32 UTC
