### ISSUE TITLE
[0] Error while opening file in editor.

### ISSUE THREAD

**Issue by SDOT2345** [microsoft/vscode-edge-devtools#646] opened 2021-11-14 08:50 UTC
**Version:**
        1.4.1

        **OS:**
        

        **Stack :**
        Could not open document. No workspace mapping was found for 'https://yoorvision.com/static/styles/all-responsive-white.css%3Fv=7.3'.

        **Additional context:**

**Comment by codepo8** [comment] 2021-11-19 12:58
No extra information given

Duplicate of #605

**Closed by codepo8** 2021-11-19 12:58 UTC
