### ISSUE TITLE
not work and panel is blank

### ISSUE THREAD

**Issue by nangongmo** [microsoft/vscode-edge-devtools#336] opened 2021-04-02 20:19 UTC
![image](https://user-images.githubusercontent.com/74093067/113451001-a3f64200-9433-11eb-9b58-edc56e2c13cd.png)
open url after click `+`,and edge devtools panel is blank

**Comment by ReinRalle** [comment] 2021-04-03 06:44
Can i confirm!

**Comment by nangongmo** [comment] 2021-04-03 16:15
@ReinRalle I'm use macos and run server in vite.js or create-react-app,no web root dir.

**Comment by ReinRalle** [comment] 2021-04-03 16:22
@nangongmo: Seems to be the same problem for me :unamused:

**Comment by codepo8** [comment] 2021-04-05 13:09
This seems to be a regression bug on Mac, we're looking into it. Thank you for reporting it.

**Comment by ReinRalle** [comment] 2021-04-05 14:59
> .. a regression bug on Mac ..

The `regression bug` occurs also under windows!

**Comment by nangongmo** [comment] 2021-04-06 12:03
@ReinRalle I found another plugin like this, [vite vscode](https://marketplace.visualstudio.com/items?itemName=antfu.vite) and work fine 
![image](https://user-images.githubusercontent.com/74093067/113707756-f32dc280-9712-11eb-8589-29b0b2235344.png)

**Comment by codepo8** [comment] 2021-04-06 13:05
> > .. a regression bug on Mac ..
> 
> The `regression bug` occurs also with windows!

We tried to replicate this across Mac and PC and can't do it, could you help us by providing the version number you're using and if there is any debugging log in the output? 
![image](https://user-images.githubusercontent.com/13508/113715146-73d7c900-96e9-11eb-9962-534fb5346ad4.png)

We're sorry about this experience, and would like to know more.

**Comment by ReinRalle** [comment] 2021-04-06 13:38
@codepo8:

* which version you mean?
  * `VsCode`: 1.55.0
  * `ms-edgedevtools.vscode-edge-devtools`: 1.1.6

* My `OUTPUT - Extensions` shows no log. (**btw:** Is there no more detailed log than about "OUTPUT" for extensions? )

**Comment by Aarklendoia** [comment] 2021-04-07 06:16
Same problem for me:

Version : 1.55.0 (user setup)
Commit : c185983a683d14c396952dd432459097bc7f757f
Date : 2021-03-30T16:01:55.261Z
Electron : 11.3.0
Chrome : 87.0.4280.141
Node.js : 12.18.3
V8 : 8.7.220.31-electron.0
OS : Windows_NT x64 10.0.19043

I use Edge 89.0.774.68 with two session (a personnal and a professionnal).

No problem with the previous version 1.1.4.

**Comment by mliao95** [comment] 2021-04-07 19:01
Thanks for reporting and commenting on this issue.  This bug is caused when the OS' language is set to anything other than English.  Currently, the extension does not support localization and does not have the necessary files to translate the text in the DevTools which is causing this break.

We will create a fix for this bug and patch the 1.1.6 release when we can.  Thank you all for your patience!

**Comment by ReinRalle** [comment] 2021-04-07 20:01
@mliao95: So why didn't the problem already appear in version 1.1.4?

**Comment by mliao95** [comment] 2021-04-07 20:17
From 1.1.4 to 1.1.6, we updated the version of the extension DevTools to version 88.0.705.9 of the browser DevTools.  Within this update, there was localization work done that did not translate well when ported over to the extension.

**Comment by mliao95** [comment] 2021-04-07 21:47
This issue should now be resolved in the newest version in the marketplace (1.1.7)!  Closing the issue and will re-activate if this still repros for anyone

**Closed by mliao95** 2021-04-07 21:47 UTC
Labels: P0, bug
