### ISSUE TITLE
Cursor property not working

### ISSUE THREAD

**Issue by miniloda** [microsoft/vscode-edge-devtools#1113] opened 2022-07-17 05:05 UTC
**Environment (please complete the following information):**
 - OS (Ubuntu 22.04 LTS):
 - Extension version (2.1.0):

**Describe the bug:**

cursor doesn't work
**Repro steps:**

Create an element in html and then just implement a state in css (e.g. hover).
**Expected behavior:**

cursor changes.

**Additional context:**

![image](https://user-images.githubusercontent.com/90799133/179384678-4627569b-a1a0-4ec2-9f61-bc5ec8803d72.png)

**Comment by codepo8** [comment] 2022-07-18 15:05
Good catch, let's see if we can replicate this.

**Comment by codepo8** [comment] 2022-10-25 18:02
This is a duplicate of the mobile cursor scenario and we will track it there. Thank you.

**Closed by codepo8** 2022-10-25 18:02 UTC
Labels: bug, tracked
