### ISSUE TITLE
[0] Error while getting the list of targets

### ISSUE THREAD

**Issue by Jc3455025** [microsoft/vscode-edge-devtools#653] opened 2021-11-16 19:40 UTC
**Version:**
        1.4.1

        **OS:**
        

        **Stack :**
        Error: getaddrinfo ENOTFOUND http

        **Additional context:**

**Comment by codepo8** [comment] 2021-11-19 12:58
No extra information given

Duplicate of #605

**Closed by codepo8** 2021-11-19 12:58 UTC
