### ISSUE TITLE
How can we set the Edge extension as the default browser for live server?

### ISSUE THREAD

**Issue by omutwar** [microsoft/vscode-edge-devtools#1639] opened 2023-07-24 03:54 UTC
I have installed Microsoft Edge Extension into VS Code editor. 

and when I click on 'Open with Liver Server', it's always opening the external default browser. instead of opening external browser and VS Code, I am exploring the possibility to set this extension as the default browser (at least for VS Code); so that when I click on 'Open with Live Server', preferably it opens inside the VS Code with the Edge extension. 

PS: I have searched online to see if I can do this, but most of the answers seems to be telling I can go to settings and pick Edge as the default browser, but then it opens with the external Edge browser, not the extension I have installed. 

If there is already support for this feature, my apologies, I missed to find it. If this was not provided yet, can you please consider adding this in the future releases, so it would be very helpful for us. 

I hope I am not the only one wishing for this! :-) 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by captainbrosset** [comment] 2023-07-24 08:02
Thanks for reaching out. No, there is no current support for this feature. But this has been requested before, so it's definitely on our backlog. We just haven't had the chance to prioritize it yet.
I'll close this issue as a duplicate of #1453 which we are using to track this already.
Thanks!

**Closed by captainbrosset** 2023-07-24 08:02 UTC

**Comment by omutwar** [comment] 2023-07-30 04:40
Thank you for your response!

Looking forward to some updates sometime in the future.
