### ISSUE TITLE
[0] Error while mirroring css content to document.

### ISSUE THREAD

**Issue by bfm90** [microsoft/vscode-edge-devtools#854] opened 2022-02-03 06:44 UTC
**Version:**
        1.4.2

        **OS:**
        

        **Stack :**
        Could not mirror css changes to document. No workspace mapping was found for 'inspector:///C:/Users/S258149/Downloads/New%20folder%20(6)/web/Responsive%20Portfolio%20Website/Responsive%20Portfolio%20Website/inspector-stylesheet'.

        **Additional context:**

**Comment by captainbrosset** [comment] 2022-02-03 10:38
Closing this one as a duplicate of #748.

**Closed by captainbrosset** 2022-02-03 10:38 UTC
