### ISSUE TITLE
Integrate the react developer tools

### ISSUE THREAD

**Issue by naranjoDeveloper** [microsoft/vscode-edge-devtools#1959] opened 2024-01-19 04:04 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by captainbrosset** [comment] 2024-01-19 09:29
Thanks for filing. I'm closing this as a duplicate of #1039 since it's already tracked there.

**Closed by captainbrosset** 2024-01-19 09:29 UTC
