### ISSUE TITLE
vs  code

### ISSUE THREAD

**Issue by mokshdudeja** [microsoft/vscode-edge-devtools#900] opened 2022-02-22 05:51 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by captainbrosset** [comment] 2022-02-22 09:26
Closing this as there is no information here that can help understand what the issue is.

**Closed by captainbrosset** 2022-02-22 09:26 UTC

**Comment by mokshdudeja** [comment] 2022-03-18 09:58
Some features are not working

**Comment by captainbrosset** [comment] 2022-03-18 10:10
Thanks for getting back to me. But I'll need more information to act on this bug here. Can you explain which features don't work exactly, and the exact steps you take that lead to the issues?
Thanks.

**Comment by mokshdudeja** [comment] 2022-03-19 18:30
I am not able to login GitHub account

**Comment by captainbrosset** [comment] 2022-03-21 08:32
This does not seem related to the vscode-edge-devtools extension then (which this repo is about). If you can't login to your GitHub account from VS Code, then you should reach out to the VSCode team here: https://github.com/microsoft/vscode
