### ISSUE TITLE
I can't launch the Elements tool for debugging nor combine it with a debugger extension through a launch.json config

### ISSUE THREAD

**Issue by paulgildea** [microsoft/vscode-edge-devtools#47] opened 2019-06-12 22:27 UTC
I want to be able to combine launching the Elements tool extension with the Debugger tool extension: https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-edge in my launch.json config

**Comment by paulgildea** [comment] 2019-06-28 03:46
Dupe of #54

**Comment by jalissia** [comment] 2019-07-25 22:59
I feel this is actually a separate issue now that I've started implementation. So I'm going to reopen (since I have a fix for the other but not this one yet)

**Comment by vidorteg** [comment] 2020-02-12 00:44
Duplicate of #68 , although this was reported first, I'm closing this one as #68 provides more details and it has the same author.

**Closed by vidorteg** 2020-02-12 00:44 UTC
Labels: P1, bug
