### ISSUE TITLE
unable download Devtools for the current target

### ISSUE THREAD

**Issue by a-irawan96** [microsoft/vscode-edge-devtools#756] opened 2021-12-12 01:52 UTC
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10):
 - Extension version (*e.g.,* 1.2.3):

**Describe the bug:**

**Repro steps:**

**Expected behavior:**

**Additional context:**

**Comment by codepo8** [comment] 2021-12-15 17:28
Duplicate of known issue, thank you.

**Closed** 2021-12-29 15:04 UTC
