### ISSUE TITLE
i want auto sync available in microsoft browser

### ISSUE THREAD

**Issue by Pratikmohod** [microsoft/vscode-edge-devtools#1634] opened 2023-07-18 16:04 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

```[tasklist]
### Tasks
```

**Comment by captainbrosset** [comment] 2023-07-19 07:42
I think this is a duplicate of #1453. Closing now.

**Closed by captainbrosset** 2023-07-19 07:42 UTC
